### ISSUE TITLE
Leaf won with stomping tantrum

### ISSUE THREAD

**Issue by GingerBumbleBee** [iriv24/pokeemerald-expansion#3]
### Description

Hello, idk if this was randomized or not but Triathlete Grace on Route 124 had a leafeon that knew stomping tantrum. I looked it up and haven’t seen a website that says it can learn that move at all. 

### Version

beta

### Discord contact info

The sunbird/gingerbumblebee

**Comment by iriv24** [comment]
closing as leafeon is intended to learn stomping tantrum
